"""Initial data

Revision ID: 532453370ca9
Revises: a4d78d8f9043
Create Date: 2017-11-28 11:40:36.460798
"""

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision = '532453370ca9'
down_revision = 'a4d78d8f9043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('print_checkin_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('webhookurl', sa.String(), nullable=False),
    sa.Column('ticket_template_id', sa.Integer(), nullable=False),
    sa.Column('send_json', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], [u'events.events.id'], name=op.f('fk_print_checkin_settings_event_id_events')),
    sa.ForeignKeyConstraint(['ticket_template_id'], [u'indico.designer_templates.id'], name=op.f('fk_print_checkin_settings_ticket_template_id_designer_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_print_checkin_settings')),
    schema='plugin_print_checkin'
    )
    op.create_index(op.f('ix_print_checkin_settings_event_id'), 'print_checkin_settings', ['event_id'], unique=False, schema='plugin_print_checkin')
    op.create_index(op.f('ix_print_checkin_settings_ticket_template_id'), 'print_checkin_settings', ['ticket_template_id'], unique=False, schema='plugin_print_checkin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_print_checkin_settings_ticket_template_id'), table_name='print_checkin_settings', schema='plugin_print_checkin')
    op.drop_index(op.f('ix_print_checkin_settings_event_id'), table_name='print_checkin_settings', schema='plugin_print_checkin')
    op.drop_table('print_checkin_settings', schema='plugin_print_checkin')
    # ### end Alembic commands ###
